### ISSUE TITLE
No entry confirmation is presented when entering a new PIN

### ISSUE THREAD

**Issue by ndizazzo** [hivewallet/hive-ios#29] opened 2014-08-14 15:39 UTC
**Issue Description:** When creating a new wallet, the user is not prompted a second time to confirm their PIN, allowing for incorrect entries.

**Reproduction Steps:** 
1. Create a new wallet and follow the on-screen instructions. 
2. Enter a new PIN when prompted
3. Observe that a second entry prompt for the PIN is not presented

I accidentally tapped the wrong PIN and wasn't able to figure out why I couldn't get back into my wallet until I made the same pin entry mistake again (thankfully I was watching what I entered when I got back in!)

**Comment by weilu** [comment] 2014-08-14 16:00
Sound like we want to avoid pin being mis-entered on set screen. Would allowing users to review their pin before proceeding serve the purpose? Perhaps we can get away with adding the submit button back to the the set pin page (making it not auto submit)? @jenbennings @haustraliaer thoughts?

**Comment by weilu** [comment] 2014-08-14 16:08
@ndizazzo fwiw, pin is resettable by entering it wrong 5 times, then you will be asked to enter your passphrase followed by setting a new pin, so it's not a huge penalty if you mistyped your pin when you set it. We have plans on making the reset proces more straightforward: https://github.com/hivewallet/hive-js/issues/80

**Comment by ndizazzo** [comment] 2014-08-14 20:14
@weilu I think an explicit submit step would serve the same purpose as a confirmation - as long as the textfields for the PIN don't have to be masked.

**Comment by jenbennings** [comment] 2014-08-15 01:27
As it stands we are re-using the same PIN entry module for both creation and return. I agree that this is not a great experience.

I'm happy to bring the submit button back as a short-term solution to this problem.

**Comment by weilu** [comment] 2014-08-15 01:39
Closing this as a duplicate of https://github.com/hivewallet/hive-js/issues/196

**Closed as completed by weilu** 2014-08-15 01:39 UTC
